title: Code4Projects
email: sasadangelo@gmail.com
description: Code4Projects is a website about software programming where I write everything I learnt in over 30 years of experience.
url: "https://www.code4projects.org"
baseurl: ""
copyright: Code4Projects, Copyright Salvatore D'Angelo © 2016-2026.
logo: assets/img/code4projects-logo-mini.webp

author:
  name: Salvatore D'Angelo
  twitter: code4projects

twitter:
  username: code4projects

# Google Analytics
google_analytics: G-62DF79P0NY
google_site_verification: DOd2vjP70sDXbIq93jN9j4P-jI5jjd9WKCXnWt7VoFs

sass:
  style: compressed

# Typography configuration
fonts:
    size: 30px
    family: Roboto Slab

collections:
  authors:
    output: true

# Code Highlighter
## 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge
highlight:
  line_number: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:slug/
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:slug/
page_excerpts: "true"

pagination:
  permalink: '/page/:num/'
  enabled: true
  per_page: 7
  sort_reverse: true
  sort_field: 'date'
  title: ':title (page :num)'
  indexpage: 'index'
  trail:
    before: 2
    after: 2

latest_posts: 5

sidebars:
  post_sidebar

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-redirect-from

exclude:
  - utility
  - resources/
